#!/bin/bash

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=linux;;
    Darwin*)    machine=darwin;;
esac

VENV="${PWD##*/}.venv"

test -d $VENV || python3 -m venv $VENV || return
$VENV/bin/pip install -r requirements.txt

. $VENV/bin/activate

TERRAFORM_VERSION=0.14.10
if ! command terraform version --json | grep $TERRAFORM_VERSION
then
curl -L -o terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${machine}_amd64.zip"
unzip terraform.zip -d .
mv terraform $VENV/bin/
rm terraform.zip
fi
